# Generated by Django 5.2.18 on 2026-10-06 15:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import events.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('country_code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Use a two-letter uppercase country code.')])),
                ('timezone', models.CharField(default='UTC', max_length=64, validators=[events.models.validate_timezone])),
                ('currency', models.CharField(blank=True, default='', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a three-letter uppercase currency code.')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name', 'country_code'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=2000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('venue_name', models.CharField(blank=True, max_length=300)),
                ('address', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('price_status', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(blank=True, default='', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a three-letter uppercase currency code.')])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=12)),
                ('is_published', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, max_length=2000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='events', to='events.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.city')),
            ],
            options={
                'ordering': ['start_date', 'start_time', 'title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=210, unique=True)),
                ('connector', models.CharField(choices=[('jsonld', 'JSON-LD event page'), ('ical', 'iCalendar feed')], max_length=30)),
                ('url', models.URLField(max_length=2000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('config', models.JSONField(blank=True, default=dict, validators=[events.models.validate_config])),
                ('enabled', models.BooleanField(default=True)),
                ('interval_minutes', models.PositiveIntegerField(default=360, validators=[django.core.validators.MinValueValidator(1)])),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='events.city')),
            ],
            options={
                'ordering': ['city__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to='events.source')),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SourceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=2000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_listings', to='events.event')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='events.source')),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['city', 'is_published', 'start_date'], name='event_city_publish_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['city', 'status', 'start_date'], name='event_city_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='event_end_date_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount__isnull', True), ('price_amount__gte', 0), _connector='OR'), name='event_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('interval_minutes__gte', 1)), name='source_interval_positive'),
        ),
        migrations.AddIndex(
            model_name='importrun',
            index=models.Index(fields=['source', '-started_at'], name='import_source_started_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcelisting',
            index=models.Index(fields=['source', 'last_seen_at'], name='listing_source_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcelisting',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_external_id'),
        ),
    ]
