# Generated by Django 5.2.18 on 2026-10-06 15:40

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=160, unique=True, validators=[events.models.validate_city_slug]),
        ),
    ]
